apiVersion: v1
kind: Service

metadata:
  name: gpu-inference

spec:
  selector:
    app: gpu-inference

  ports:
    - port: {{ .Values.gpuInference.port }}
      targetPort: {{ .Values.gpuInference.port }}

  type: ClusterIP